_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.15
            "5": 0.18.6
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
DEVICE:
    value: cuda:0
batch_size:
    value: 256
epochs:
    value: 30
opt_lr:
    value: 0.0002
opt_weight_decay:
    value: 0.0001
wandb:
    value: true
